spring:
  datasource:
    url: jdbc:h2:mem:maindb
    username: sa

  liquibase:
    enabled: true

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true

  jmx:
    enabled: true

  data:
    rest:
      basePath: /datarest

management:
  endpoints:
    web:
      exposure:
        include: "health, info, metrics, loggers, logfile"
  endpoint:
    logfile:
      external-file: hw16/logs/app.log
    health:
      show-details: always
  health:
    defaults:
      enabled: true

info:
  build:
    location: classpath:/META-INF/build-info.properties

