spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres

  liquibase:
    enabled: true

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  jmx:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "health, info, metrics, loggers, logfile"
  endpoint:
    logfile:
      external-file: hw16/logs/app.log
    health:
      show-details: always
  health:
    defaults:
      enabled: true

info:
  build:
    location: classpath:/META-INF/build-info.properties

logging:
  level:
    ROOT: ERROR