spring:
  messages:
    baseName: messages
    encoding: UTF-8
    fallbackToSystemLocale: false
test:
  rightAnswersCountToPass: 3
  maxInputAttempts: 10
  testFileName: questions.csv
  locale: en-US
  fileNameByLocaleTag:
    ru-RU: questions_ru.csv
    en-US: questions.csv